"use client";

import { useState, useEffect, useRef, use } from "react";
import Link from "next/link";
import {
  Home, ChevronRight, FileDown, Share2, Sparkles,
  Play, Loader2, AlertCircle, RefreshCw, Wand2, MessageCircle, X, Send,
} from "lucide-react";
import { api } from "@/features/auth/lib/api";
import { cn } from "@/lib/utils";
import { formatIdeaDate } from "@/features/entrepreneur/hooks/useIdeas";
import { useAiPipeline } from "@/features/entrepreneur/hooks/useAiPipeline";
import type { SectionState, SectionKey } from "@/features/entrepreneur/hooks/useAiPipeline";
import type { Idea } from "@/features/entrepreneur/types/idea";

import { CustomersSection }       from "@/features/entrepreneur/components/analysis/CustomersSection";
import { CompetitionSection }     from "@/features/entrepreneur/components/analysis/CompetitionSection";
import { MarketPotentialSection } from "@/features/entrepreneur/components/analysis/MarketPotentialSection";
import { BusinessModelSection }   from "@/features/entrepreneur/components/analysis/BusinessModelSection";
import { MvpPlanningSection }     from "@/features/entrepreneur/components/analysis/MvpPlanningSection";
import { ProblemsSection }        from "@/features/entrepreneur/components/analysis/ProblemsSection";
import { UnitEconomicsSection }   from "@/features/entrepreneur/components/analysis/UnitEconomicsSection";
import { IdeaStrategySection }    from "@/features/entrepreneur/components/analysis/IdeaStrategySection";
import type { SkillsGap }         from "@/features/entrepreneur/types/idea";

// ─── Tabs ─────────────────────────────────────────────────────────────────────

type TabKey =
  | "overview"
  | "customers"
  | "competition"
  | "market"
  | "businessModel"
  | "mvp"
  | "risk"
  | "financial";

const TABS: { key: TabKey; label: string }[] = [
  { key: "overview",      label: "Overview"           },
  { key: "customers",     label: "Customers"          },
  { key: "competition",   label: "Competitor Analysis"},
  { key: "market",        label: "Market"             },
  { key: "businessModel", label: "Business Model"     },
  { key: "mvp",           label: "MVP"                },
  { key: "risk",          label: "Risk"               },
  { key: "financial",     label: "Financial"          },
];

// ─── Tab content ──────────────────────────────────────────────────────────────

// Maps each tab to the SectionKey used for generating it. Null means no standalone endpoint.
const TAB_SECTION_KEY: Record<Exclude<TabKey, "overview">, SectionKey | null> = {
  customers:     "customers",
  competition:   "competition",
  market:        "marketPotential",
  businessModel: "businessModel",
  mvp:           "mvpPlanning",
  risk:          null, // problems is generated by the full pipeline
  financial:     "unitEconomics",
};

// Maps each tab to the section state key
const TAB_STATE_KEY: Record<Exclude<TabKey, "overview">, SectionKey> = {
  customers:     "customers",
  competition:   "competition",
  market:        "marketPotential",
  businessModel: "businessModel",
  mvp:           "mvpPlanning",
  risk:          "problems",
  financial:     "unitEconomics",
};

function TabContent({
  tab,
  idea,
  sections,
  hasRun,
  onRun,
  onRunSection,
  isRunning,
}: {
  tab: TabKey;
  idea: Idea;
  sections: ReturnType<typeof useAiPipeline>["sections"];
  hasRun: boolean;
  onRun: () => void;
  onRunSection: (key: SectionKey) => void;
  isRunning: boolean;
}) {
  if (tab === "overview") {
    return <OverviewSection idea={idea} sections={sections} hasRun={hasRun} onRun={onRun} isRunning={isRunning} />;
  }

  const sectionMap: Record<Exclude<TabKey, "overview">, React.ReactNode> = {
    customers:     <CustomersSection       {...sections.customers}       />,
    competition:   <CompetitionSection     {...sections.competition}     />,
    market:        <MarketPotentialSection {...sections.marketPotential} />,
    businessModel: <BusinessModelSection   {...sections.businessModel}   />,
    mvp:           <MvpPlanningSection     {...sections.mvpPlanning}     />,
    risk:          <ProblemsSection        {...sections.problems}        />,
    financial:     <UnitEconomicsSection   {...sections.unitEconomics}   />,
  };

  const stateKey = TAB_STATE_KEY[tab as Exclude<TabKey, "overview">];
  const s = sections[stateKey] as SectionState;

  if (!s.data && !s.isLoading) {
    const sectionKey = TAB_SECTION_KEY[tab as Exclude<TabKey, "overview">];
    const handleRun = sectionKey ? () => onRunSection(sectionKey) : onRun;
    return <SectionCallToAction onRun={handleRun} isRunning={isRunning} />;
  }

  return <>{sectionMap[tab as Exclude<TabKey, "overview">]}</>;
}

function OverviewSection({
  idea,
  sections,
  hasRun,
  onRun,
  isRunning,
}: {
  idea: Idea;
  sections: ReturnType<typeof useAiPipeline>["sections"];
  hasRun: boolean;
  onRun: () => void;
  isRunning: boolean;
}) {
  return (
    <div className="flex flex-col gap-6">
      {/* Idea meta card */}
      <div className="bg-card rounded-xl border border-border p-6 flex flex-col gap-5">
        <div className="flex items-start justify-between gap-4 flex-wrap">
          <div className="flex flex-col gap-1">
            <h3 className="text-base font-semibold text-foreground">Idea Overview</h3>
            <p className="text-sm text-muted-foreground leading-relaxed max-w-2xl whitespace-pre-wrap">
              {idea.description}
            </p>
          </div>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 pt-2 border-t border-border">
          <MetaStat label="Budget" value={idea.budget != null ? `$${idea.budget.toLocaleString()}` : "—"} />
          <MetaStat label="Feasibility" value={idea.feasibility != null ? `${idea.feasibility} / 10` : "—"} />
          <MetaStat label="Status" value={idea.status ?? "—"} />
        </div>

        {idea.skills && !Array.isArray(idea.skills) && (
          <SkillsAnalysis skills={idea.skills as SkillsGap} />
        )}
      </div>

      {/* AI Strategy */}
      {hasRun || sections.ideaStrategy.data || sections.ideaStrategy.isLoading ? (
        <IdeaStrategySection {...sections.ideaStrategy} />
      ) : (
        <PipelineCallToAction onRun={onRun} isRunning={isRunning} />
      )}
    </div>
  );
}

function MetaStat({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-xs text-muted-foreground uppercase tracking-wide">{label}</p>
      <p className="text-sm font-semibold text-foreground mt-0.5 capitalize">{value}</p>
    </div>
  );
}

function SkillsAnalysis({ skills }: { skills: SkillsGap }) {
  const groups: { label: string; items: string[]; color: string }[] = [
    { label: "Your Skills",      items: skills.your_skills     ?? [], color: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400" },
    { label: "Required Skills",  items: skills.required_skills ?? [], color: "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400" },
    { label: "Skill Gaps",       items: skills.skill_gaps      ?? [], color: "bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400" },
  ].filter((g) => g.items.length > 0);

  if (groups.length === 0) return null;

  return (
    <div className="bg-card rounded-xl border border-border p-5 flex flex-col gap-4">
      <h3 className="text-sm font-semibold text-foreground">Skills Analysis</h3>
      <div className="flex flex-col gap-3">
        {groups.map(({ label, items, color }) => (
          <div key={label} className="flex flex-col gap-1.5">
            <p className="text-xs text-muted-foreground uppercase tracking-wide">{label}</p>
            <div className="flex flex-wrap gap-1.5">
              {items.map((skill) => (
                <span key={skill} className={cn("px-2.5 py-0.5 rounded-full text-xs font-medium", color)}>
                  {skill}
                </span>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function SectionCallToAction({ onRun, isRunning }: { onRun: () => void; isRunning: boolean }) {
  return (
    <div className="flex flex-col items-center justify-center h-72 gap-5 rounded-2xl border-2 border-dashed border-border bg-card">
      <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-amber-500 to-yellow-400 flex items-center justify-center shadow-[0_4px_16px_rgba(255,183,3,0.3)]">
        <Sparkles size={22} className="text-white" />
      </div>
      <div className="text-center space-y-1.5 px-6">
        <h3 className="text-base font-semibold text-foreground">No analysis yet</h3>
        <p className="text-sm text-muted-foreground max-w-xs">
          Generate AI insights for this section.
        </p>
      </div>
      <button
        type="button"
        onClick={onRun}
        disabled={isRunning}
        className={cn(
          "flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-medium text-white cursor-pointer transition-opacity",
          "bg-gradient-to-r from-amber-500 to-yellow-500 shadow-[0_2px_12px_rgba(255,183,3,0.3)]",
          isRunning && "opacity-60 cursor-not-allowed"
        )}
      >
        {isRunning ? <Loader2 size={15} className="animate-spin" /> : <Play size={15} />}
        {isRunning ? "Generating…" : "Generate Analysis"}
      </button>
    </div>
  );
}

function PipelineCallToAction({ onRun, isRunning }: { onRun: () => void; isRunning: boolean }) {
  return (
    <div className="flex flex-col items-center justify-center h-72 gap-5 rounded-2xl border-2 border-dashed border-border bg-card">
      <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-amber-500 to-yellow-400 flex items-center justify-center shadow-[0_4px_16px_rgba(255,183,3,0.3)]">
        <Sparkles size={22} className="text-white" />
      </div>
      <div className="text-center space-y-1.5 px-6">
        <h3 className="text-base font-semibold text-foreground">No analysis yet</h3>
        <p className="text-sm text-muted-foreground max-w-xs">
          Run the AI pipeline to generate in-depth insights for this idea.
        </p>
      </div>
      <button
        type="button"
        onClick={onRun}
        disabled={isRunning}
        className={cn(
          "flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-medium text-white cursor-pointer transition-opacity",
          "bg-gradient-to-r from-amber-500 to-yellow-500 shadow-[0_2px_12px_rgba(255,183,3,0.3)]",
          isRunning && "opacity-60 cursor-not-allowed"
        )}
      >
        {isRunning ? <Loader2 size={15} className="animate-spin" /> : <Play size={15} />}
        {isRunning ? "Running…" : "Run Pipeline"}
      </button>
    </div>
  );
}

// ─── Section chat popup ───────────────────────────────────────────────────────

const SECTION_CHAT_SLUG: Partial<Record<SectionKey, string>> = {
  customers:       "customers",
  competition:     "competition",
  marketPotential: "market-potential",
  ideaStrategy:    "idea-strategy",
  businessModel:   "business-model",
  functionsList:   "functions-list",
  mvpPlanning:     "mvp-planning",
  unitEconomics:   "unit-economics",
  goToMarket:      "go-to-market",
  problems:        "problems",
};

const SECTION_LABEL: Partial<Record<SectionKey, string>> = {
  customers:       "Customers",
  competition:     "Competition",
  marketPotential: "Market",
  ideaStrategy:    "Strategy",
  businessModel:   "Business Model",
  functionsList:   "Functions",
  mvpPlanning:     "MVP",
  unitEconomics:   "Financial",
  goToMarket:      "Go-to-Market",
  problems:        "Risk",
};

interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

function SectionChatPopup({
  sectionKey,
  ideaId,
  onClose,
}: {
  sectionKey: SectionKey;
  ideaId: string;
  onClose: () => void;
}) {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [inputValue, setInputValue] = useState("");
  const [isStreaming, setIsStreaming] = useState(false);
  const [sessionId, setSessionId] = useState<string | null>(null);
  const [loadingSession, setLoadingSession] = useState(true);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const abortRef = useRef<AbortController | null>(null);
  const slug = SECTION_CHAT_SLUG[sectionKey];
  const label = SECTION_LABEL[sectionKey] ?? sectionKey;

  // Find the latest existing session for this section+idea, or create one
  useEffect(() => {
    let cancelled = false;
    async function initSession() {
      setLoadingSession(true);
      try {
        // Look for an existing session for this section + idea
        const params = new URLSearchParams();
        if (slug) params.set("section_slug", slug);
        if (ideaId) params.set("idea_id", ideaId);
        const existing = await api.get(`/chat/sessions?${params.toString()}`);
        const sessions: Array<{ id: string }> = existing.data;

        let sid: string;
        if (sessions.length > 0) {
          // Reuse the most recent session
          sid = sessions[0].id;
        } else {
          // Create a new session
          const res = await api.post("/chat/sessions", {
            section_slug: slug,
            idea_id: ideaId || undefined,
            title: `${label} Chat`,
          });
          sid = res.data.id;
        }

        if (cancelled) return;
        setSessionId(sid);

        // Load last 10 messages
        const msgsRes = await api.get(`/chat/sessions/${sid}/messages?limit=10`);
        if (cancelled) return;
        const loaded: ChatMessage[] = (msgsRes.data as Array<{ role: string; content: string }>).map((m) => ({
          role: m.role as "user" | "assistant",
          content: m.content,
        }));
        setMessages(loaded);
      } catch {
        // Non-fatal: popup works without persistence
      } finally {
        if (!cancelled) setLoadingSession(false);
      }
    }
    initSession();
    return () => { cancelled = true; };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  const sendMessage = async () => {
    const text = inputValue.trim();
    if (!text || isStreaming || !slug) return;

    const history = messages;
    setInputValue("");
    setMessages((prev) => [...prev, { role: "user", content: text }]);
    setIsStreaming(true);
    setMessages((prev) => [...prev, { role: "assistant", content: "" }]);

    const ctrl = new AbortController();
    abortRef.current = ctrl;
    let assistantText = "";

    try {
      const response = await fetch(`/api/ai/${slug}/chat/stream`, {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          message: text,
          history: history.map((m) => ({ role: m.role, content: m.content })),
          idea_id: ideaId || undefined,
        }),
        signal: ctrl.signal,
      });

      if (!response.ok || !response.body) throw new Error("Stream failed");

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = "";

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split("\n");
        buffer = lines.pop() ?? "";

        for (const line of lines) {
          if (!line.startsWith("data: ")) continue;
          const jsonStr = line.slice(6).trim();
          if (!jsonStr || jsonStr === "[DONE]") continue;
          try {
            const parsed = JSON.parse(jsonStr);
            if (parsed.type === "token" && parsed.content) {
              assistantText += parsed.content;
              setMessages((prev) => {
                const copy = [...prev];
                copy[copy.length - 1] = { role: "assistant", content: assistantText };
                return copy;
              });
            }
          } catch { /* ignore malformed chunks */ }
        }
      }

      // Save both messages to DB session
      if (sessionId && assistantText) {
        try {
          await api.post(`/chat/sessions/${sessionId}/messages`, {
            messages: [
              { role: "user", content: text },
              { role: "assistant", content: assistantText },
            ],
          });
        } catch {
          // Non-fatal: messages displayed locally even if save fails
        }
      }
    } catch (err) {
      if ((err as Error).name === "AbortError") return;
      setMessages((prev) => {
        const copy = [...prev];
        copy[copy.length - 1] = { role: "assistant", content: "Sorry, something went wrong. Please try again." };
        return copy;
      });
    } finally {
      setIsStreaming(false);
      abortRef.current = null;
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  };

  return (
    <div className="fixed bottom-6 right-6 z-50 flex flex-col w-[360px] max-w-[calc(100vw-2rem)] h-[500px] max-h-[calc(100vh-5rem)] bg-white dark:bg-neutral-900 rounded-2xl shadow-2xl border border-neutral-200 dark:border-neutral-700 overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-neutral-200 dark:border-neutral-700 bg-gradient-to-r from-amber-500 to-yellow-500 rounded-t-2xl">
        <div className="flex items-center gap-2">
          <MessageCircle size={15} className="text-white" />
          <span className="text-sm font-semibold text-white">{label} — AI Chat</span>
        </div>
        <div className="flex items-center gap-1">
          {sessionId && (
            <a
              href={`/entrepreneur/ai-chat?session_id=${sessionId}`}
              target="_blank"
              rel="noopener noreferrer"
              className="text-[10px] text-white/80 hover:text-white underline underline-offset-2 transition-colors px-1"
            >
              View full chat
            </a>
          )}
          <button
            type="button"
            onClick={onClose}
            className="p-1 rounded-lg hover:bg-white/20 transition-colors cursor-pointer"
          >
            <X size={15} className="text-white" />
          </button>
        </div>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto px-4 py-3 flex flex-col gap-3">
        {loadingSession && (
          <div className="flex items-center justify-center mt-4">
            <Loader2 size={16} className="animate-spin text-amber-400" />
          </div>
        )}
        {!loadingSession && messages.length === 0 && (
          <p className="text-xs text-muted-foreground text-center mt-4">
            Ask anything about the {label} analysis.
          </p>
        )}
        {messages.map((msg, i) => (
          <div
            key={i}
            className={cn(
              "max-w-[85%] px-3 py-2 rounded-xl text-sm leading-relaxed whitespace-pre-wrap",
              msg.role === "user"
                ? "self-end bg-amber-500 text-white rounded-br-sm"
                : "self-start bg-neutral-100 dark:bg-neutral-800 text-foreground rounded-bl-sm"
            )}
          >
            {msg.content}
            {msg.role === "assistant" && msg.content === "" && isStreaming && (
              <span className="inline-block w-1.5 h-3.5 bg-neutral-400 dark:bg-neutral-500 rounded-sm animate-pulse ml-0.5" />
            )}
          </div>
        ))}
        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <div className="border-t border-neutral-200 dark:border-neutral-700 px-3 py-2.5 flex items-end gap-2">
        <textarea
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="Ask about this section…"
          rows={1}
          disabled={isStreaming || loadingSession}
          className="flex-1 resize-none text-sm bg-neutral-100 dark:bg-neutral-800 border-0 rounded-xl px-3 py-2 focus:outline-none focus:ring-2 focus:ring-amber-400 text-foreground placeholder:text-muted-foreground max-h-28 overflow-y-auto"
          style={{ lineHeight: "1.4" }}
        />
        <button
          type="button"
          onClick={sendMessage}
          disabled={isStreaming || !inputValue.trim() || loadingSession}
          className={cn(
            "p-2.5 rounded-xl bg-amber-500 text-white flex-shrink-0 transition-opacity cursor-pointer",
            (isStreaming || !inputValue.trim() || loadingSession) && "opacity-40 cursor-not-allowed"
          )}
        >
          {isStreaming
            ? <Loader2 size={15} className="animate-spin" />
            : <Send size={15} />}
        </button>
      </div>
    </div>
  );
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function IdeaDetailPage({
  params,
}: {
  params: Promise<{ idea_id: string }>;
}) {
  const { idea_id } = use(params);
  const [idea, setIdea]     = useState<Idea | null>(null);
  const [loading, setLoading] = useState(true);
  const [fetchError, setFetchError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<TabKey>("overview");

  const { sections, isRunning, hasRun, runError, runPipeline, runSection, regenerateSection, regenerateSectionCustom } = useAiPipeline(idea_id);

  const [customPromptOpen, setCustomPromptOpen]       = useState(false);
  const [customPromptSection, setCustomPromptSection] = useState<SectionKey | null>(null);
  const [customPromptText, setCustomPromptText]       = useState("");

  const [chatPopupOpen, setChatPopupOpen]       = useState(false);
  const [chatPopupSection, setChatPopupSection] = useState<SectionKey | null>(null);

  useEffect(() => {
    api
      .get<Idea>(`/ideas/${idea_id}`)
      .then(({ data }) => setIdea(data))
      .catch(() => setFetchError("Failed to load idea."))
      .finally(() => setLoading(false));
  }, [idea_id]);

  // ── Loading / error states ──────────────────────────────────────────────────

  if (loading) {
    return (
      <div className="min-h-screen bg-neutral-100 dark:bg-neutral-900 flex items-center justify-center">
        <div className="w-6 h-6 rounded-full border-2 border-amber-400 border-t-transparent animate-spin" />
      </div>
    );
  }

  if (fetchError || !idea) {
    return (
      <div className="min-h-screen bg-neutral-100 dark:bg-neutral-900 flex items-center justify-center gap-3 text-red-500">
        <AlertCircle size={18} />
        <p className="text-sm">{fetchError ?? "Idea not found."}</p>
      </div>
    );
  }

  // ── Render ──────────────────────────────────────────────────────────────────

  return (
    <div className="min-h-screen bg-neutral-100 dark:bg-neutral-900 transition-colors">
      <main className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 pb-16">

        {/* Breadcrumb */}
        <nav className="flex items-center gap-1.5 pt-6 pb-4 text-sm text-gray-500 dark:text-gray-400">
          <Link href="/entrepreneur" className="hover:text-gray-700 dark:hover:text-gray-200 transition-colors">
            <Home size={14} />
          </Link>
          <ChevronRight size={12} className="text-gray-400" />
          <Link href="/entrepreneur/ideas" className="hover:text-gray-700 dark:hover:text-gray-200 transition-colors">
            Ideas
          </Link>
          <ChevronRight size={12} className="text-gray-400" />
          <span className="text-gray-700 dark:text-gray-200 font-medium truncate max-w-[200px]">
            {idea.title ?? "Untitled idea"}
          </span>
        </nav>

        {/* Header row */}
        <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4 mb-8">
          {/* Title + date */}
          <div className="flex flex-col gap-2">
            <h1 className="text-2xl sm:text-3xl font-semibold text-foreground">{idea.title ?? "Untitled idea"}</h1>
            <p className="text-base text-muted-foreground">{formatIdeaDate(idea.created_at)}</p>
          </div>

          {/* Actions */}
          <div className="flex items-center gap-8 shrink-0">
            {/* Pipeline status */}
            {isRunning && (
              <span className="flex items-center gap-1.5 text-xs text-amber-600 dark:text-amber-400 font-medium">
                <Loader2 size={12} className="animate-spin" />
                Running pipeline…
              </span>
            )}
            {hasRun && !isRunning && (
              <span className="text-xs text-green-600 dark:text-green-400 font-medium">
                ✓ Pipeline complete
              </span>
            )}

            {/* Icon actions */}
            <div className="flex items-center gap-1">
              <ActionIconButton label="Save as PDF" onClick={() => {}}>
                <FileDown size={18} className="text-neutral-400" />
              </ActionIconButton>
              <ActionIconButton label="Share" onClick={() => {}}>
                <Share2 size={18} className="text-neutral-400" />
              </ActionIconButton>
            </div>

            {/* Edit with AI / Run */}
            <button
              type="button"
              onClick={runPipeline}
              disabled={isRunning}
              className={cn(
                "flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium text-white cursor-pointer transition-opacity",
                "bg-gradient-to-r from-amber-500 to-yellow-500 shadow-[0_2px_16px_rgba(255,183,3,0.3)] outline outline-[0.66px] outline-yellow-500/60",
                isRunning && "opacity-60 cursor-not-allowed"
              )}
            >
              {isRunning
                ? <Loader2 size={14} className="animate-spin" />
                : <Sparkles size={14} />}
              {hasRun ? "Re-run AI" : "Edit with AI"}
            </button>
          </div>
        </div>

        {runError && (
          <p className="mb-4 text-sm text-red-500 bg-red-50 dark:bg-red-900/20 px-3 py-2 rounded-lg">
            {runError}
          </p>
        )}

        {/* Tab bar + section action icons */}
        {(() => {
          const activeSectionKey = activeTab !== "overview"
            ? TAB_STATE_KEY[activeTab as Exclude<TabKey, "overview">]
            : null;
          const activeSectionHasData = activeSectionKey ? !!sections[activeSectionKey].data : false;
          const activeSectionLoading = activeSectionKey ? sections[activeSectionKey].isLoading : false;

          return (
            <div className="flex items-center gap-2 mb-8">
              <div className="flex-1 min-w-0 px-2 py-1.5 bg-gray-200 dark:bg-neutral-800 rounded-lg flex items-center gap-1 overflow-x-auto scrollbar-hide">
                {TABS.map(({ key, label }) => {
                  const active = activeTab === key;
                  return (
                    <button
                      key={key}
                      type="button"
                      onClick={() => setActiveTab(key)}
                      className={cn(
                        "shrink-0 min-h-10 px-4 py-2 rounded-xl text-sm font-medium transition-all cursor-pointer whitespace-nowrap",
                        active
                          ? "bg-white dark:bg-neutral-700 text-foreground shadow-sm border border-neutral-300 dark:border-neutral-600"
                          : "text-neutral-600 dark:text-neutral-400 hover:bg-white/50 dark:hover:bg-neutral-700/50"
                      )}
                    >
                      {label}
                    </button>
                  );
                })}
              </div>

              {/* Section action icons — only when the active tab has data */}
              {activeSectionHasData && activeSectionKey && (
                <div className="flex items-center gap-0.5 shrink-0">
                  <SectionIconButton
                    tooltip="Regenerate"
                    disabled={activeSectionLoading}
                    onClick={() => regenerateSection(activeSectionKey)}
                  >
                    <RefreshCw size={16} />
                  </SectionIconButton>
                  <SectionIconButton
                    tooltip="Regenerate with custom prompt"
                    disabled={activeSectionLoading}
                    onClick={() => {
                      setCustomPromptSection(activeSectionKey);
                      setCustomPromptText("");
                      setCustomPromptOpen(true);
                    }}
                  >
                    <Wand2 size={16} />
                  </SectionIconButton>
                  <SectionIconButton
                    tooltip="Chat with AI"
                    onClick={() => { setChatPopupSection(activeSectionKey); setChatPopupOpen(true); }}
                  >
                    <MessageCircle size={16} />
                  </SectionIconButton>
                </div>
              )}
            </div>
          );
        })()}

        {/* Custom prompt modal */}
        {customPromptOpen && (
          <div
            className="fixed inset-0 bg-black/40 flex items-center justify-center z-50"
            onClick={() => setCustomPromptOpen(false)}
          >
            <div
              className="bg-white dark:bg-neutral-800 rounded-2xl shadow-xl p-6 w-full max-w-md mx-4 flex flex-col gap-4"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-semibold text-foreground">Custom Regeneration</h3>
                <button
                  type="button"
                  onClick={() => setCustomPromptOpen(false)}
                  className="p-1 rounded-lg hover:bg-neutral-100 dark:hover:bg-neutral-700 transition-colors cursor-pointer"
                >
                  <X size={15} className="text-neutral-500" />
                </button>
              </div>
              <textarea
                value={customPromptText}
                onChange={(e) => setCustomPromptText(e.target.value)}
                placeholder="Describe what you want to change or focus on…"
                rows={4}
                className="w-full text-sm border border-border rounded-xl p-3 resize-none bg-transparent focus:outline-none focus:ring-2 focus:ring-amber-400 text-foreground placeholder:text-muted-foreground"
                autoFocus
              />
              <button
                type="button"
                disabled={!customPromptText.trim()}
                onClick={() => {
                  if (customPromptSection && customPromptText.trim()) {
                    regenerateSectionCustom(customPromptSection, customPromptText.trim());
                    setCustomPromptOpen(false);
                    setCustomPromptText("");
                  }
                }}
                className={cn(
                  "flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium text-white transition-opacity cursor-pointer",
                  "bg-gradient-to-r from-amber-500 to-yellow-500 shadow-[0_2px_12px_rgba(255,183,3,0.3)]",
                  !customPromptText.trim() && "opacity-50 cursor-not-allowed"
                )}
              >
                <Wand2 size={14} />
                Generate
              </button>
            </div>
          </div>
        )}

        {/* Tab content */}
        <TabContent
          tab={activeTab}
          idea={idea}
          sections={sections}
          hasRun={hasRun}
          onRun={runPipeline}
          onRunSection={runSection}
          isRunning={isRunning}
        />
      </main>

      {/* Section chat popup */}
      {chatPopupOpen && chatPopupSection && (
        <SectionChatPopup
          key={chatPopupSection}
          sectionKey={chatPopupSection}
          ideaId={idea_id}
          onClose={() => setChatPopupOpen(false)}
        />
      )}
    </div>
  );
}

function ActionIconButton({
  label,
  onClick,
  children,
}: {
  label: string;
  onClick: () => void;
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col items-center">
      <button
        type="button"
        onClick={onClick}
        className="p-2 rounded-lg hover:bg-neutral-200 dark:hover:bg-neutral-700 transition-colors cursor-pointer"
      >
        {children}
      </button>
      <span className="text-[8px] font-medium text-neutral-400 leading-6">{label}</span>
    </div>
  );
}

function SectionIconButton({
  tooltip,
  onClick,
  disabled,
  children,
}: {
  tooltip: string;
  onClick: () => void;
  disabled?: boolean;
  children: React.ReactNode;
}) {
  return (
    <div className="relative group">
      <button
        type="button"
        onClick={onClick}
        disabled={disabled}
        className={cn(
          "p-2 rounded-lg hover:bg-neutral-200 dark:hover:bg-neutral-700 transition-colors cursor-pointer text-neutral-500 dark:text-neutral-400",
          disabled && "opacity-40 cursor-not-allowed"
        )}
      >
        {children}
      </button>
      <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-1.5 px-2 py-1 bg-neutral-800 dark:bg-neutral-100 text-white dark:text-neutral-900 text-xs rounded-md whitespace-nowrap opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none z-20">
        {tooltip}
      </div>
    </div>
  );
}
