"use client";

import { useState, useEffect, useRef, use } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  Home, ChevronRight, FileDown, Share2, Sparkles,
  Play, Loader2, AlertCircle, RefreshCw, Wand2, MessageCircle, X, Send,
  CheckCircle2, PlusCircle, RotateCcw,
} from "lucide-react";
import { api } from "@/features/auth/lib/api";
import { cn } from "@/lib/utils";
import { formatIdeaDate } from "@/features/entrepreneur/hooks/useIdeas";
import { useAiPipeline } from "@/features/entrepreneur/hooks/useAiPipeline";
import type { SectionState, SectionKey } from "@/features/entrepreneur/hooks/useAiPipeline";
import type { Idea } from "@/features/entrepreneur/types/idea";

import { CustomersSection }       from "@/features/entrepreneur/components/analysis/CustomersSection";
import { CompetitionSection }     from "@/features/entrepreneur/components/analysis/CompetitionSection";
import { MarketPotentialSection } from "@/features/entrepreneur/components/analysis/MarketPotentialSection";
import { IdeaStrategySection }    from "@/features/entrepreneur/components/analysis/IdeaStrategySection";
import { BusinessModelSection }   from "@/features/entrepreneur/components/analysis/BusinessModelSection";
import { FunctionsListSection }   from "@/features/entrepreneur/components/analysis/FunctionsListSection";
import { MvpPlanningSection }     from "@/features/entrepreneur/components/analysis/MvpPlanningSection";
import { UnitEconomicsSection }   from "@/features/entrepreneur/components/analysis/UnitEconomicsSection";
import { GoToMarketSection }      from "@/features/entrepreneur/components/analysis/GoToMarketSection";
import { ProblemsSection }        from "@/features/entrepreneur/components/analysis/ProblemsSection";
import type { SkillsGap }         from "@/features/entrepreneur/types/idea";

// ─── Tabs ─────────────────────────────────────────────────────────────────────

type TabKey =
  | "overview"
  | "problems"
  | "customers"
  | "competition"
  | "market"
  | "strategy"
  | "businessModel"
  | "functions"
  | "mvp"
  | "financial"
  | "goToMarket";

const TABS: { key: TabKey; label: string }[] = [
  { key: "overview",      label: "Overview"           },
  { key: "problems",      label: "Problems"           },
  { key: "customers",     label: "Customers"          },
  { key: "competition",   label: "Competitor Analysis"},
  { key: "market",        label: "Market"             },
  { key: "strategy",      label: "Strategy"           },
  { key: "businessModel", label: "Business Model"     },
  { key: "functions",     label: "Functions"          },
  { key: "mvp",           label: "MVP"                },
  { key: "financial",     label: "Financial"          },
  { key: "goToMarket",    label: "Go-to-Market"       },
];

// ─── Tab content ──────────────────────────────────────────────────────────────

// Maps each tab to the SectionKey used for generating it. Null means no standalone endpoint.
const TAB_SECTION_KEY: Record<Exclude<TabKey, "overview">, SectionKey | null> = {
  problems:      null, // generated by the full pipeline
  customers:     "customers",
  competition:   "competition",
  market:        "marketPotential",
  strategy:      "ideaStrategy",
  businessModel: "businessModel",
  functions:     "functionsList",
  mvp:           "mvpPlanning",
  financial:     "unitEconomics",
  goToMarket:    "goToMarket",
};

// Maps each tab to the section state key
const TAB_STATE_KEY: Record<Exclude<TabKey, "overview">, SectionKey> = {
  problems:      "problems",
  customers:     "customers",
  competition:   "competition",
  market:        "marketPotential",
  strategy:      "ideaStrategy",
  businessModel: "businessModel",
  functions:     "functionsList",
  mvp:           "mvpPlanning",
  financial:     "unitEconomics",
  goToMarket:    "goToMarket",
};

function TabContent({
  tab,
  idea,
  sections,
  onRun,
  onRunSection,
  isRunning,
}: {
  tab: TabKey;
  idea: Idea;
  sections: ReturnType<typeof useAiPipeline>["sections"];
  onRun: () => void;
  onRunSection: (key: SectionKey) => void;
  isRunning: boolean;
}) {
  if (tab === "overview") {
    return <OverviewSection idea={idea} sections={sections} onRun={onRun} isRunning={isRunning} />;
  }

  const sectionMap: Record<Exclude<TabKey, "overview">, React.ReactNode> = {
    problems:      <ProblemsSection        {...sections.problems}        />,
    customers:     <CustomersSection       {...sections.customers}       />,
    competition:   <CompetitionSection     {...sections.competition}     />,
    market:        <MarketPotentialSection {...sections.marketPotential} />,
    strategy:      <IdeaStrategySection    {...sections.ideaStrategy}    />,
    businessModel: <BusinessModelSection   {...sections.businessModel}   />,
    functions:     <FunctionsListSection   {...sections.functionsList}   />,
    mvp:           <MvpPlanningSection     {...sections.mvpPlanning}     />,
    financial:     <UnitEconomicsSection   {...sections.unitEconomics}   />,
    goToMarket:    <GoToMarketSection      {...sections.goToMarket}      />,
  };

  const stateKey = TAB_STATE_KEY[tab as Exclude<TabKey, "overview">];
  const s = sections[stateKey] as SectionState;

  if (!s.data && !s.isLoading) {
    const sectionKey = TAB_SECTION_KEY[tab as Exclude<TabKey, "overview">];
    const handleRun = sectionKey ? () => onRunSection(sectionKey) : onRun;
    return <SectionCallToAction onRun={handleRun} isRunning={isRunning} />;
  }

  return <>{sectionMap[tab as Exclude<TabKey, "overview">]}</>;
}

function OverviewSection({
  idea,
  sections,
  onRun,
  isRunning,
}: {
  idea: Idea;
  sections: ReturnType<typeof useAiPipeline>["sections"];
  onRun: () => void;
  isRunning: boolean;
}) {
  return (
    <div className="flex flex-col gap-6">
      {/* Idea meta card */}
      <div className="bg-card rounded-xl border border-border p-6 flex flex-col gap-5">
        <div className="flex items-start justify-between gap-4 flex-wrap">
          <div className="flex flex-col gap-1">
            <h3 className="text-base font-semibold text-foreground">Idea Overview</h3>
            <p className="text-sm text-muted-foreground leading-relaxed max-w-2xl whitespace-pre-wrap">
              {idea.description}
            </p>
          </div>
        </div>

        <div className="grid grid-cols-2 sm:grid-cols-3 gap-4 pt-2 border-t border-border">
          <MetaStat label="Budget" value={idea.budget != null ? `$${idea.budget.toLocaleString()}` : "—"} />
          <MetaStat label="Feasibility" value={idea.feasibility != null ? `${idea.feasibility} / 10` : "—"} />
          <MetaStat label="Status" value={idea.status ?? "—"} />
        </div>

        {idea.skills && !Array.isArray(idea.skills) && (
          <SkillsAnalysis skills={idea.skills as SkillsGap} />
        )}
      </div>

      {/* Pipeline CTA */}
      {!sections.problems.data && !sections.problems.isLoading && (
        <PipelineCallToAction onRun={onRun} isRunning={isRunning} />
      )}
    </div>
  );
}

function MetaStat({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-xs text-muted-foreground uppercase tracking-wide">{label}</p>
      <p className="text-sm font-semibold text-foreground mt-0.5 capitalize">{value}</p>
    </div>
  );
}

function SkillsAnalysis({ skills }: { skills: SkillsGap }) {
  const groups: { label: string; items: string[]; color: string }[] = [
    { label: "Your Skills",      items: skills.your_skills     ?? [], color: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400" },
    { label: "Required Skills",  items: skills.required_skills ?? [], color: "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400" },
    { label: "Skill Gaps",       items: skills.skill_gaps      ?? [], color: "bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400" },
  ].filter((g) => g.items.length > 0);

  if (groups.length === 0) return null;

  return (
    <div className="bg-card rounded-xl border border-border p-5 flex flex-col gap-4">
      <h3 className="text-sm font-semibold text-foreground">Skills Analysis</h3>
      <div className="flex flex-col gap-3">
        {groups.map(({ label, items, color }) => (
          <div key={label} className="flex flex-col gap-1.5">
            <p className="text-xs text-muted-foreground uppercase tracking-wide">{label}</p>
            <div className="flex flex-wrap gap-1.5">
              {items.map((skill) => (
                <span key={skill} className={cn("px-2.5 py-0.5 rounded-full text-xs font-medium", color)}>
                  {skill}
                </span>
              ))}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}

function SectionCallToAction({ onRun, isRunning }: { onRun: () => void; isRunning: boolean }) {
  return (
    <div className="flex flex-col items-center justify-center h-72 gap-5 rounded-2xl border-2 border-dashed border-border bg-card">
      <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-amber-500 to-yellow-400 flex items-center justify-center shadow-[0_4px_16px_rgba(255,183,3,0.3)]">
        <Sparkles size={22} className="text-white" />
      </div>
      <div className="text-center space-y-1.5 px-6">
        <h3 className="text-base font-semibold text-foreground">No analysis yet</h3>
        <p className="text-sm text-muted-foreground max-w-xs">
          Generate AI insights for this section.
        </p>
      </div>
      <button
        type="button"
        onClick={onRun}
        disabled={isRunning}
        className={cn(
          "flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-medium text-white cursor-pointer transition-opacity",
          "bg-gradient-to-r from-amber-500 to-yellow-500 shadow-[0_2px_12px_rgba(255,183,3,0.3)]",
          isRunning && "opacity-60 cursor-not-allowed"
        )}
      >
        {isRunning ? <Loader2 size={15} className="animate-spin" /> : <Play size={15} />}
        {isRunning ? "Generating…" : "Generate Analysis"}
      </button>
    </div>
  );
}

function PipelineCallToAction({ onRun, isRunning }: { onRun: () => void; isRunning: boolean }) {
  return (
    <div className="flex flex-col items-center justify-center h-72 gap-5 rounded-2xl border-2 border-dashed border-border bg-card">
      <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-amber-500 to-yellow-400 flex items-center justify-center shadow-[0_4px_16px_rgba(255,183,3,0.3)]">
        <Sparkles size={22} className="text-white" />
      </div>
      <div className="text-center space-y-1.5 px-6">
        <h3 className="text-base font-semibold text-foreground">No analysis yet</h3>
        <p className="text-sm text-muted-foreground max-w-xs">
          Run the AI pipeline to generate in-depth insights for this idea.
        </p>
      </div>
      <button
        type="button"
        onClick={onRun}
        disabled={isRunning}
        className={cn(
          "flex items-center gap-2 px-5 py-2.5 rounded-xl text-sm font-medium text-white cursor-pointer transition-opacity",
          "bg-gradient-to-r from-amber-500 to-yellow-500 shadow-[0_2px_12px_rgba(255,183,3,0.3)]",
          isRunning && "opacity-60 cursor-not-allowed"
        )}
      >
        {isRunning ? <Loader2 size={15} className="animate-spin" /> : <Play size={15} />}
        {isRunning ? "Running…" : "Run Pipeline"}
      </button>
    </div>
  );
}

// ─── Edit Idea Chat Modal ─────────────────────────────────────────────────────

interface EditChatMessage {
  role: "user" | "assistant";
  content: string;
}

interface IdeaIntake {
  idea_summary: string;
  industry?: string;
  target_users?: string[];
  problem_assumption?: string;
  solution_assumption?: string;
  business_model?: string;
  region?: string;
}

function IdeaEditChatModal({
  idea,
  ideaId,
  onClose,
  onSectionsReset,
}: {
  idea: Idea;
  ideaId: string;
  onClose: () => void;
  onSectionsReset: () => void;
}) {
  const router = useRouter();
  const [messages, setMessages] = useState<EditChatMessage[]>([]);
  const [history, setHistory]   = useState<Array<{ role: string; content: string }>>([]);
  const [inputValue, setInputValue] = useState("");
  const [isSending, setIsSending]   = useState(false);
  const [readyIntake, setReadyIntake] = useState<IdeaIntake | null>(null);
  const [approveStep, setApproveStep] = useState<"chat" | "approved" | "done">("chat");
  const [actionLoading, setActionLoading] = useState(false);
  const [actionError, setActionError]     = useState<string | null>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const abortRef = useRef<AbortController | null>(null);

  // Auto-scroll
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  // Send the opening message automatically on mount
  useEffect(() => {
    const opening = `I want to refine my idea "${idea.title ?? "my idea"}". Here's what I have so far: ${idea.description ?? "no description yet"}. Please help me improve and structure it.`;
    sendMessage(opening, []);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const sendMessage = async (text: string, currentHistory: typeof history) => {
    if (!text.trim() || isSending) return;
    setMessages((prev) => [...prev, { role: "user", content: text }, { role: "assistant", content: "" }]);
    setIsSending(true);
    setInputValue("");

    const ctrl = new AbortController();
    abortRef.current = ctrl;
    let assistantText = "";

    try {
      const response = await fetch("/api/ai/idea-intake/chat/stream", {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ message: text, history: currentHistory }),
        signal: ctrl.signal,
      });

      if (!response.ok || !response.body) throw new Error("Stream failed");

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = "";

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split("\n");
        buffer = lines.pop() ?? "";

        for (const line of lines) {
          if (!line.startsWith("data: ")) continue;
          const jsonStr = line.slice(6).trim();
          if (!jsonStr || jsonStr === "[DONE]") continue;

          try {
            const parsed = JSON.parse(jsonStr);

            if (parsed.type === "token" && parsed.content) {
              assistantText += parsed.content;
              setMessages((prev) => {
                const copy = [...prev];
                copy[copy.length - 1] = { role: "assistant", content: assistantText };
                return copy;
              });
            } else if (parsed.type === "done") {
              const newHistory = [
                ...currentHistory,
                { role: "user",      content: text },
                { role: "assistant", content: assistantText },
              ];
              if (parsed.status === "ready" && parsed.intake) {
                setReadyIntake(parsed.intake);
                setApproveStep("approved");
                setHistory(newHistory);
              } else {
                setHistory(parsed.history ?? newHistory);
              }
            }
          } catch { /* skip malformed SSE events */ }
        }
      }
    } catch (err: unknown) {
      if (err instanceof Error && err.name === "AbortError") return;
      setMessages((prev) => {
        const copy = [...prev];
        copy[copy.length - 1] = { role: "assistant", content: "Sorry, something went wrong. Please try again." };
        return copy;
      });
    } finally {
      setIsSending(false);
    }
  };

  const handleSend = () => sendMessage(inputValue, history);

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const handleUpdateIdea = async () => {
    if (!readyIntake) return;
    setActionLoading(true);
    setActionError(null);
    try {
      // 1. Update idea description with the new intake summary
      await api.patch(`/ideas/${ideaId}`, {
        description: readyIntake.idea_summary,
      });
      // 2. Clear all AI analysis for this idea so it can be re-run fresh
      await api.delete(`/ai/ideas/${ideaId}/analysis`);
      // 3. Reset section state in the parent and close
      onSectionsReset();
      setApproveStep("done");
      setTimeout(() => onClose(), 800);
    } catch {
      setActionError("Failed to update the idea. Please try again.");
    } finally {
      setActionLoading(false);
    }
  };

  const handleCreateNew = async () => {
    if (!readyIntake) return;
    setActionLoading(true);
    setActionError(null);
    try {
      const title = `${idea.title ?? "Idea"} (Refined)`;
      const res = await api.post("/ideas/", {
        title,
        description: readyIntake.idea_summary,
      });
      const newId: string = res.data.id;
      onClose();
      router.push(`/entrepreneur/ideas/${newId}`);
    } catch {
      setActionError("Failed to create new idea. Please try again.");
    } finally {
      setActionLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
      <div className="w-full max-w-2xl h-[90vh] max-h-[700px] bg-white dark:bg-neutral-900 rounded-2xl shadow-2xl flex flex-col overflow-hidden border border-neutral-200 dark:border-neutral-700">

        {/* Header */}
        <div className="flex items-center justify-between px-5 py-3.5 border-b border-neutral-200 dark:border-neutral-700 bg-gradient-to-r from-amber-500 to-yellow-500">
          <div className="flex items-center gap-2.5">
            <Sparkles size={16} className="text-white" />
            <span className="text-sm font-semibold text-white">Edit Idea with AI</span>
            {approveStep === "approved" && (
              <span className="bg-white/20 text-white text-[10px] font-semibold px-2 py-0.5 rounded-full">
                Idea Ready ✓
              </span>
            )}
          </div>
          <button
            type="button"
            onClick={onClose}
            className="p-1.5 rounded-lg hover:bg-white/20 transition-colors cursor-pointer"
          >
            <X size={15} className="text-white" />
          </button>
        </div>

        {/* Messages */}
        <div className="flex-1 overflow-y-auto px-5 py-4 flex flex-col gap-3">
          {messages.map((msg, i) => (
            <div
              key={i}
              className={cn(
                "max-w-[88%] px-4 py-2.5 rounded-2xl text-sm leading-relaxed whitespace-pre-wrap",
                msg.role === "user"
                  ? "self-end bg-amber-500 text-white rounded-br-sm"
                  : "self-start bg-neutral-100 dark:bg-neutral-800 text-foreground rounded-bl-sm"
              )}
            >
              {msg.content}
              {msg.role === "assistant" && msg.content === "" && isSending && (
                <span className="inline-flex gap-1 items-center">
                  <span className="w-1.5 h-1.5 bg-neutral-400 rounded-full animate-bounce [animation-delay:0ms]" />
                  <span className="w-1.5 h-1.5 bg-neutral-400 rounded-full animate-bounce [animation-delay:150ms]" />
                  <span className="w-1.5 h-1.5 bg-neutral-400 rounded-full animate-bounce [animation-delay:300ms]" />
                </span>
              )}
            </div>
          ))}

          {/* Approval card — shown when agent is done */}
          {approveStep === "approved" && readyIntake && (
            <div className="self-stretch mt-2 bg-gradient-to-br from-amber-50 to-yellow-50 dark:from-amber-900/20 dark:to-yellow-900/20 border border-amber-200 dark:border-amber-700 rounded-2xl p-4 flex flex-col gap-4">
              <div className="flex items-center gap-2">
                <CheckCircle2 size={16} className="text-amber-600" />
                <span className="text-sm font-semibold text-amber-800 dark:text-amber-300">Idea structured — what would you like to do?</span>
              </div>
              <div className="text-xs text-neutral-600 dark:text-neutral-400 leading-relaxed border-l-2 border-amber-300 pl-3">
                {readyIntake.idea_summary}
              </div>
              {actionError && (
                <p className="text-xs text-red-500">{actionError}</p>
              )}
              <div className="flex flex-col gap-2">
                <button
                  type="button"
                  onClick={handleUpdateIdea}
                  disabled={actionLoading}
                  className={cn(
                    "flex items-center gap-2.5 px-4 py-2.5 rounded-xl text-sm font-medium text-white transition-opacity cursor-pointer",
                    "bg-gradient-to-r from-amber-500 to-yellow-500 shadow-[0_2px_12px_rgba(255,183,3,0.3)]",
                    actionLoading && "opacity-60 cursor-not-allowed"
                  )}
                >
                  {actionLoading ? <Loader2 size={14} className="animate-spin" /> : <RotateCcw size={14} />}
                  Update this idea (clear old analysis)
                </button>
                <button
                  type="button"
                  onClick={handleCreateNew}
                  disabled={actionLoading}
                  className={cn(
                    "flex items-center gap-2.5 px-4 py-2.5 rounded-xl text-sm font-medium transition-opacity cursor-pointer",
                    "bg-white dark:bg-neutral-800 border border-neutral-200 dark:border-neutral-600 text-foreground",
                    actionLoading && "opacity-60 cursor-not-allowed"
                  )}
                >
                  {actionLoading ? <Loader2 size={14} className="animate-spin" /> : <PlusCircle size={14} />}
                  Save as new idea (keep original + its analysis)
                </button>
                <button
                  type="button"
                  onClick={() => { setApproveStep("chat"); setReadyIntake(null); }}
                  disabled={actionLoading}
                  className="text-xs text-muted-foreground hover:text-foreground transition-colors cursor-pointer text-left pl-1"
                >
                  ← Keep chatting to refine further
                </button>
              </div>
            </div>
          )}

          {approveStep === "done" && (
            <div className="self-center mt-4 flex items-center gap-2 text-green-600 dark:text-green-400 text-sm font-medium">
              <CheckCircle2 size={16} />
              Idea updated! Closing…
            </div>
          )}

          <div ref={messagesEndRef} />
        </div>

        {/* Input — hidden after approval */}
        {approveStep === "chat" && (
          <div className="border-t border-neutral-200 dark:border-neutral-700 px-4 py-3 flex items-end gap-2">
            <textarea
              value={inputValue}
              onChange={(e) => setInputValue(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Describe your idea or answer the agent's questions…"
              rows={2}
              disabled={isSending}
              className="flex-1 resize-none text-sm bg-neutral-100 dark:bg-neutral-800 border-0 rounded-xl px-3 py-2 focus:outline-none focus:ring-2 focus:ring-amber-400 text-foreground placeholder:text-muted-foreground max-h-32 overflow-y-auto"
            />
            <button
              type="button"
              onClick={handleSend}
              disabled={isSending || !inputValue.trim()}
              className={cn(
                "p-2.5 rounded-xl bg-amber-500 text-white flex-shrink-0 transition-opacity cursor-pointer",
                (isSending || !inputValue.trim()) && "opacity-40 cursor-not-allowed"
              )}
            >
              {isSending ? <Loader2 size={15} className="animate-spin" /> : <Send size={15} />}
            </button>
          </div>
        )}
      </div>
    </div>
  );
}

// ─── Section chat popup ───────────────────────────────────────────────────────

const SECTION_CHAT_SLUG: Partial<Record<SectionKey, string>> = {
  customers:       "customers",
  competition:     "competition",
  marketPotential: "market-potential",
  ideaStrategy:    "idea-strategy",
  businessModel:   "business-model",
  functionsList:   "functions-list",
  mvpPlanning:     "mvp-planning",
  unitEconomics:   "unit-economics",
  goToMarket:      "go-to-market",
  problems:        "problems",
};

const SECTION_LABEL: Partial<Record<SectionKey, string>> = {
  customers:       "Customers",
  competition:     "Competition",
  marketPotential: "Market",
  ideaStrategy:    "Strategy",
  businessModel:   "Business Model",
  functionsList:   "Functions",
  mvpPlanning:     "MVP",
  unitEconomics:   "Financial",
  goToMarket:      "Go-to-Market",
  problems:        "Problems",
};

interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

function SectionChatPopup({
  sectionKey,
  ideaId,
  onClose,
}: {
  sectionKey: SectionKey;
  ideaId: string;
  onClose: () => void;
}) {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [inputValue, setInputValue] = useState("");
  const [isStreaming, setIsStreaming] = useState(false);
  const [sessionId, setSessionId] = useState<string | null>(null);
  const [loadingSession, setLoadingSession] = useState(true);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const abortRef = useRef<AbortController | null>(null);
  const slug = SECTION_CHAT_SLUG[sectionKey];
  const label = SECTION_LABEL[sectionKey] ?? sectionKey;

  // Find the latest existing session for this section+idea, or create one
  useEffect(() => {
    let cancelled = false;
    async function initSession() {
      setLoadingSession(true);
      try {
        // Look for an existing session for this section + idea
        const params = new URLSearchParams();
        if (slug) params.set("section_slug", slug);
        if (ideaId) params.set("idea_id", ideaId);
        const existing = await api.get(`/chat/sessions?${params.toString()}`);
        const sessions: Array<{ id: string }> = existing.data;

        let sid: string;
        if (sessions.length > 0) {
          // Reuse the most recent session
          sid = sessions[0].id;
        } else {
          // Create a new session
          const res = await api.post("/chat/sessions", {
            section_slug: slug,
            idea_id: ideaId || undefined,
            title: `${label} Chat`,
          });
          sid = res.data.id;
        }

        if (cancelled) return;
        setSessionId(sid);

        // Load last 10 messages
        const msgsRes = await api.get(`/chat/sessions/${sid}/messages?limit=10`);
        if (cancelled) return;
        const loaded: ChatMessage[] = (msgsRes.data as Array<{ role: string; content: string }>).map((m) => ({
          role: m.role as "user" | "assistant",
          content: m.content,
        }));
        setMessages(loaded);
      } catch {
        // Non-fatal: popup works without persistence
      } finally {
        if (!cancelled) setLoadingSession(false);
      }
    }
    initSession();
    return () => { cancelled = true; };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  const sendMessage = async () => {
    const text = inputValue.trim();
    if (!text || isStreaming || !slug) return;

    const history = messages;
    setInputValue("");
    setMessages((prev) => [...prev, { role: "user", content: text }]);
    setIsStreaming(true);
    setMessages((prev) => [...prev, { role: "assistant", content: "" }]);

    const ctrl = new AbortController();
    abortRef.current = ctrl;
    let assistantText = "";

    try {
      const response = await fetch(`/api/ai/${slug}/chat/stream`, {
        method: "POST",
        credentials: "include",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          message: text,
          history: history.map((m) => ({ role: m.role, content: m.content })),
          idea_id: ideaId || undefined,
        }),
        signal: ctrl.signal,
      });

      if (!response.ok || !response.body) throw new Error("Stream failed");

      const reader = response.body.getReader();
      const decoder = new TextDecoder();
      let buffer = "";

      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buffer += decoder.decode(value, { stream: true });
        const lines = buffer.split("\n");
        buffer = lines.pop() ?? "";

        for (const line of lines) {
          if (!line.startsWith("data: ")) continue;
          const jsonStr = line.slice(6).trim();
          if (!jsonStr || jsonStr === "[DONE]") continue;
          try {
            const parsed = JSON.parse(jsonStr);
            if (parsed.type === "token" && parsed.content) {
              assistantText += parsed.content;
              setMessages((prev) => {
                const copy = [...prev];
                copy[copy.length - 1] = { role: "assistant", content: assistantText };
                return copy;
              });
            }
          } catch { /* ignore malformed chunks */ }
        }
      }

      // Save both messages to DB session
      if (sessionId && assistantText) {
        try {
          await api.post(`/chat/sessions/${sessionId}/messages`, {
            messages: [
              { role: "user", content: text },
              { role: "assistant", content: assistantText },
            ],
          });
        } catch {
          // Non-fatal: messages displayed locally even if save fails
        }
      }
    } catch (err) {
      if ((err as Error).name === "AbortError") return;
      setMessages((prev) => {
        const copy = [...prev];
        copy[copy.length - 1] = { role: "assistant", content: "Sorry, something went wrong. Please try again." };
        return copy;
      });
    } finally {
      setIsStreaming(false);
      abortRef.current = null;
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  };

  return (
    <div className="fixed bottom-6 right-6 z-50 flex flex-col w-[360px] max-w-[calc(100vw-2rem)] h-[500px] max-h-[calc(100vh-5rem)] bg-white dark:bg-neutral-900 rounded-2xl shadow-2xl border border-neutral-200 dark:border-neutral-700 overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-neutral-200 dark:border-neutral-700 bg-gradient-to-r from-amber-500 to-yellow-500 rounded-t-2xl">
        <div className="flex items-center gap-2">
          <MessageCircle size={15} className="text-white" />
          <span className="text-sm font-semibold text-white">{label} — AI Chat</span>
        </div>
        <div className="flex items-center gap-1">
          {sessionId && (
            <a
              href={`/entrepreneur/ai-chat?session_id=${sessionId}`}
              target="_blank"
              rel="noopener noreferrer"
              className="text-[10px] text-white/80 hover:text-white underline underline-offset-2 transition-colors px-1"
            >
              View full chat
            </a>
          )}
          <button
            type="button"
            onClick={onClose}
            className="p-1 rounded-lg hover:bg-white/20 transition-colors cursor-pointer"
          >
            <X size={15} className="text-white" />
          </button>
        </div>
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto px-4 py-3 flex flex-col gap-3">
        {loadingSession && (
          <div className="flex items-center justify-center mt-4">
            <Loader2 size={16} className="animate-spin text-amber-400" />
          </div>
        )}
        {!loadingSession && messages.length === 0 && (
          <p className="text-xs text-muted-foreground text-center mt-4">
            Ask anything about the {label} analysis.
          </p>
        )}
        {messages.map((msg, i) => (
          <div
            key={i}
            className={cn(
              "max-w-[85%] px-3 py-2 rounded-xl text-sm leading-relaxed whitespace-pre-wrap",
              msg.role === "user"
                ? "self-end bg-amber-500 text-white rounded-br-sm"
                : "self-start bg-neutral-100 dark:bg-neutral-800 text-foreground rounded-bl-sm"
            )}
          >
            {msg.content}
            {msg.role === "assistant" && msg.content === "" && isStreaming && (
              <span className="inline-block w-1.5 h-3.5 bg-neutral-400 dark:bg-neutral-500 rounded-sm animate-pulse ml-0.5" />
            )}
          </div>
        ))}
        <div ref={messagesEndRef} />
      </div>

      {/* Input */}
      <div className="border-t border-neutral-200 dark:border-neutral-700 px-3 py-2.5 flex items-end gap-2">
        <textarea
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="Ask about this section…"
          rows={1}
          disabled={isStreaming || loadingSession}
          className="flex-1 resize-none text-sm bg-neutral-100 dark:bg-neutral-800 border-0 rounded-xl px-3 py-2 focus:outline-none focus:ring-2 focus:ring-amber-400 text-foreground placeholder:text-muted-foreground max-h-28 overflow-y-auto"
          style={{ lineHeight: "1.4" }}
        />
        <button
          type="button"
          onClick={sendMessage}
          disabled={isStreaming || !inputValue.trim() || loadingSession}
          className={cn(
            "p-2.5 rounded-xl bg-amber-500 text-white flex-shrink-0 transition-opacity cursor-pointer",
            (isStreaming || !inputValue.trim() || loadingSession) && "opacity-40 cursor-not-allowed"
          )}
        >
          {isStreaming
            ? <Loader2 size={15} className="animate-spin" />
            : <Send size={15} />}
        </button>
      </div>
    </div>
  );
}

// ─── PDF export ───────────────────────────────────────────────────────────────

function safeParseJson(raw: string | null): Record<string, unknown> | null {
  if (!raw) return null;
  try {
    const parsed = JSON.parse(raw);
    return parsed && typeof parsed === "object" ? parsed : null;
  } catch {
    return null;
  }
}

function esc(s: unknown): string {
  return String(s ?? "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function strList(items: unknown[]): string {
  if (!items.length) return "";
  return `<ul>${items.map((v) => `<li>${esc(v)}</li>`).join("")}</ul>`;
}

// ─── MVP-specific PDF builder ─────────────────────────────────────────────────

interface PdfMvpData {
  mvp_goal?: string;
  summary?: string;
  riskiest_assumptions?: Array<{
    id?: string; assumption?: string; risk_level?: string;
    validation_method?: string; kill_signal?: string;
  }>;
  scope?: { included?: string[]; excluded?: string[] };
  core_user_flows?: Array<{
    id?: string; name?: string; steps?: string[]; success_metric?: string;
  }>;
  build_plan?: {
    phases?: Array<{ phase?: string | number; name?: string; tasks?: string[]; milestone?: string }>;
    total_timeline?: string;
    no_code_tools_needed?: string[];
  };
  validation_experiments?: Array<{
    id?: string; hypothesis?: string; method?: string;
    success_metric?: string; timeline?: string; cost_usd?: number;
  }>;
  launch_criteria?: { must_be_true?: string[]; success_metrics?: string[]; kill_criteria?: string[] };
  testing_plan?: Array<{ area?: string; method?: string; pass_criteria?: string }>;
  qa_checklist?: string[];
  first_100_users_plan?: string;
  source_mode?: string;
  sources_used?: number;
  sources_list?: Array<{ url?: string; title?: string }>;
}

function buildMvpPdfHtml(idea: Idea, raw: string | null): string {
  const date = idea.created_at
    ? new Date(idea.created_at).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })
    : "";

  let mvp: PdfMvpData = {};
  try {
    const p = JSON.parse(raw ?? "");
    if (p && typeof p === "object") mvp = p as PdfMvpData;
  } catch { /* render what we have */ }

  const riskBadge = (level?: string) => {
    const l = (level ?? "").toLowerCase();
    const bg = l === "high" ? "#fee2e2" : l === "medium" ? "#fef3c7" : "#d1fae5";
    const color = l === "high" ? "#b91c1c" : l === "medium" ? "#92400e" : "#065f46";
    return level
      ? `<span style="background:${bg};color:${color};padding:1px 7px;border-radius:999px;font-size:8pt;font-weight:700;text-transform:uppercase;">${esc(level)} risk</span>`
      : "";
  };

  // Goal
  const goalHtml = (mvp.mvp_goal || mvp.summary) ? `
    <section class="goal-card">
      ${mvp.mvp_goal ? `<div class="goal-label">MVP Goal</div><p class="goal-text">${esc(mvp.mvp_goal)}</p>` : ""}
      ${mvp.summary ? `<p class="summary-text">${esc(mvp.summary)}</p>` : ""}
    </section>` : "";

  // Assumptions
  const assumptionsHtml = mvp.riskiest_assumptions?.length ? `
    <section>
      <h2>Riskiest Assumptions</h2>
      <div class="grid2">
        ${mvp.riskiest_assumptions.map((a, i) => `
          <div class="card">
            <div class="card-header">
              <span class="card-id">${esc(a.id ?? `A${i + 1}`)}</span>
              ${riskBadge(a.risk_level)}
            </div>
            ${a.assumption ? `<p class="card-title">${esc(a.assumption)}</p>` : ""}
            ${a.validation_method ? `<div class="sublabel">Validation</div><p class="subtext">${esc(a.validation_method)}</p>` : ""}
            ${a.kill_signal ? `<div class="kill-signal"><span class="kill-label">Kill signal</span><p>${esc(a.kill_signal)}</p></div>` : ""}
          </div>`).join("")}
      </div>
    </section>` : "";

  // Scope
  const scopeHtml = (mvp.scope?.included?.length || mvp.scope?.excluded?.length) ? `
    <section>
      <h2>Scope</h2>
      <div class="grid2">
        <div class="card scope-in">
          <div class="scope-title green">✓ Included</div>
          ${strList(mvp.scope?.included ?? [])}
        </div>
        <div class="card scope-out">
          <div class="scope-title gray">✕ Excluded</div>
          ${strList(mvp.scope?.excluded ?? [])}
        </div>
      </div>
    </section>` : "";

  // User flows
  const flowsHtml = mvp.core_user_flows?.length ? `
    <section>
      <h2>Core User Flows</h2>
      <div class="grid2">
        ${mvp.core_user_flows.map((f, i) => `
          <div class="card">
            <div class="card-header">
              <span class="flow-badge">${esc(f.id ?? `UF${i + 1}`)}</span>
              <span class="card-title-inline">${esc(f.name ?? "Flow")}</span>
            </div>
            ${f.steps?.length ? `<ol class="steps">${f.steps.map((s) => `<li>${esc(s)}</li>`).join("")}</ol>` : ""}
            ${f.success_metric ? `<div class="metric-box"><span class="metric-label">Success metric</span><p>${esc(f.success_metric)}</p></div>` : ""}
          </div>`).join("")}
      </div>
    </section>` : "";

  // Build plan
  const buildPlanHtml = (() => {
    const bp = mvp.build_plan;
    if (!bp) return "";
    const parts: string[] = [];
    if (bp.total_timeline) parts.push(`<div class="timeline-badge">📅 Timeline: ${esc(bp.total_timeline)}</div>`);
    if (bp.phases?.length) {
      parts.push(`<div class="phases">${bp.phases.map((p, i) => `
        <div class="phase">
          <div class="phase-num">${esc(p.phase ?? i + 1)}</div>
          <div class="phase-body">
            <h4>${esc(p.name ?? `Phase ${p.phase ?? i + 1}`)}</h4>
            ${p.tasks?.length ? strList(p.tasks) : ""}
            ${p.milestone ? `<div class="milestone">🏁 ${esc(p.milestone)}</div>` : ""}
          </div>
        </div>`).join("")}</div>`);
    }
    if (bp.no_code_tools_needed?.length) {
      parts.push(`<div class="tools-section"><div class="sublabel">No-code tools</div><div class="tags">${bp.no_code_tools_needed.map((t) => `<span class="tag">${esc(t)}</span>`).join("")}</div></div>`);
    }
    return parts.length ? `<section><h2>Build Plan</h2>${parts.join("")}</section>` : "";
  })();

  // Experiments
  const experimentsHtml = mvp.validation_experiments?.length ? `
    <section>
      <h2>Validation Experiments</h2>
      <div class="grid2">
        ${mvp.validation_experiments.map((e, i) => `
          <div class="card">
            <div class="card-header">
              <span class="card-id">${esc(e.id ?? `E${i + 1}`)}</span>
              <div style="display:flex;gap:6px;">
                ${e.timeline ? `<span class="badge-cyan">📅 ${esc(e.timeline)}</span>` : ""}
                ${typeof e.cost_usd === "number" ? `<span class="badge-green">$${e.cost_usd}</span>` : ""}
              </div>
            </div>
            ${e.hypothesis ? `<p class="card-title">${esc(e.hypothesis)}</p>` : ""}
            ${e.method ? `<div class="sublabel">Method</div><p class="subtext">${esc(e.method)}</p>` : ""}
            ${e.success_metric ? `<div class="sublabel">Success metric</div><p class="subtext">${esc(e.success_metric)}</p>` : ""}
          </div>`).join("")}
      </div>
    </section>` : "";

  // Launch criteria
  const launchHtml = (() => {
    const lc = mvp.launch_criteria;
    if (!lc) return "";
    const parts: string[] = [];
    if (lc.must_be_true?.length) parts.push(`<div class="criteria-box green"><div class="crit-title green">✓ Must be true</div>${strList(lc.must_be_true)}</div>`);
    if (lc.success_metrics?.length) parts.push(`<div class="criteria-box amber"><div class="crit-title amber">⬤ Success metrics</div>${strList(lc.success_metrics)}</div>`);
    if (lc.kill_criteria?.length) parts.push(`<div class="criteria-box red"><div class="crit-title red">✕ Kill criteria</div>${strList(lc.kill_criteria)}</div>`);
    return parts.length ? `<section><h2>Launch Criteria</h2><div class="grid3">${parts.join("")}</div></section>` : "";
  })();

  // Testing
  const testingHtml = (() => {
    const parts: string[] = [];
    if (mvp.testing_plan?.length) {
      parts.push(`<table class="testing-table">
        <thead><tr><th>Area</th><th>Method</th><th>Pass Criteria</th></tr></thead>
        <tbody>${mvp.testing_plan.map((t) => `<tr><td><strong>${esc(t.area ?? "—")}</strong></td><td>${esc(t.method ?? "—")}</td><td>${esc(t.pass_criteria ?? "—")}</td></tr>`).join("")}</tbody>
      </table>`);
    }
    if (mvp.qa_checklist?.length) {
      parts.push(`<div class="sublabel" style="margin-top:12px;">QA Checklist</div>${strList(mvp.qa_checklist)}`);
    }
    return parts.length ? `<section><h2>Testing &amp; QA</h2>${parts.join("")}</section>` : "";
  })();

  // First 100 users
  const firstUsersHtml = mvp.first_100_users_plan
    ? `<section><h2>First 100 Users Plan</h2><p>${esc(mvp.first_100_users_plan)}</p></section>` : "";

  // Sources
  const sourcesHtml = (() => {
    const srcs = (mvp.sources_list ?? []).filter((s) => s.url);
    if (!srcs.length && !mvp.source_mode && mvp.sources_used == null) return "";
    return `<section><h2>Sources</h2>
      ${mvp.source_mode ? `<span class="tag">${esc(mvp.source_mode.replace(/_/g, " "))}</span>` : ""}
      ${mvp.sources_used != null ? `<span class="tag amber">${mvp.sources_used} source${mvp.sources_used !== 1 ? "s" : ""} used</span>` : ""}
      ${srcs.length ? `<ol style="margin-top:10px;">${srcs.map((s) => `<li><a href="${esc(s.url)}">${esc(s.title ?? s.url)}</a></li>`).join("")}</ol>` : ""}
    </section>`;
  })();

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>${esc(idea.title ?? "Idea")} — MVP Plan</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: -apple-system, "Segoe UI", Arial, sans-serif; color: #111; background: #fff; padding: 2cm 2.5cm; font-size: 10.5pt; line-height: 1.6; }
  h1 { font-size: 20pt; font-weight: 700; margin-bottom: 2px; }
  .meta-line { color: #666; font-size: 9.5pt; margin-bottom: 6px; }
  .desc { color: #333; font-size: 10pt; margin-bottom: 20px; max-width: 680px; white-space: pre-wrap; }
  h2 { font-size: 12.5pt; font-weight: 700; border-bottom: 2px solid #f59e0b; padding-bottom: 4px; margin: 22px 0 12px; color: #1a1a1a; }
  h4 { font-size: 10pt; font-weight: 600; margin: 0 0 4px; }
  section { break-inside: avoid; }

  /* Goal card */
  .goal-card { background: #fffbeb; border: 1px solid #fde68a; border-radius: 10px; padding: 14px 16px; margin-bottom: 4px; }
  .goal-label { font-size: 8pt; font-weight: 700; text-transform: uppercase; letter-spacing: .07em; color: #92400e; margin-bottom: 4px; }
  .goal-text { font-size: 11pt; font-weight: 600; color: #111; margin-bottom: 6px; }
  .summary-text { font-size: 10pt; color: #555; border-top: 1px solid #fde68a; padding-top: 8px; margin-top: 8px; }

  /* Grid layouts */
  .grid2 { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
  .grid3 { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 10px; }

  /* Cards */
  .card { border: 1px solid #e5e7eb; border-radius: 8px; padding: 12px; background: #fafafa; }
  .card-header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 6px; }
  .card-id { font-size: 8pt; font-weight: 700; color: #9ca3af; letter-spacing: .1em; }
  .card-title { font-size: 10pt; font-weight: 600; color: #111; margin-bottom: 6px; }
  .card-title-inline { font-size: 10pt; font-weight: 600; color: #111; }
  .sublabel { font-size: 8pt; font-weight: 700; text-transform: uppercase; letter-spacing: .06em; color: #9ca3af; margin: 6px 0 2px; }
  .subtext { font-size: 9.5pt; color: #555; }
  .kill-signal { background: #fef2f2; border: 1px solid #fecaca; border-radius: 6px; padding: 6px 10px; margin-top: 6px; }
  .kill-label { font-size: 8pt; font-weight: 700; text-transform: uppercase; color: #dc2626; letter-spacing: .06em; }
  .kill-signal p { font-size: 9pt; color: #7f1d1d; margin-top: 2px; }

  /* Scope */
  .scope-in { background: #f0fdf4; border-color: #bbf7d0; }
  .scope-out { background: #f9fafb; border-color: #e5e7eb; }
  .scope-title { font-size: 10pt; font-weight: 600; margin-bottom: 6px; }
  .scope-title.green { color: #15803d; }
  .scope-title.gray { color: #6b7280; }

  /* User flows */
  .flow-badge { background: #f3e8ff; color: #7e22ce; font-size: 8.5pt; font-weight: 700; padding: 2px 7px; border-radius: 6px; }
  .steps { padding-left: 18px; font-size: 9.5pt; color: #333; }
  .steps li { margin-bottom: 2px; }
  .metric-box { background: #faf5ff; border: 1px solid #e9d5ff; border-radius: 6px; padding: 6px 10px; margin-top: 8px; }
  .metric-label { font-size: 8pt; font-weight: 700; text-transform: uppercase; color: #7e22ce; letter-spacing: .06em; }

  /* Build plan */
  .timeline-badge { display: inline-block; background: #fffbeb; border: 1px solid #fde68a; border-radius: 999px; padding: 3px 12px; font-size: 9pt; font-weight: 600; color: #92400e; margin-bottom: 10px; }
  .phases { display: flex; flex-direction: column; gap: 10px; }
  .phase { display: flex; gap: 10px; align-items: flex-start; }
  .phase-num { min-width: 26px; height: 26px; background: #f59e0b; color: #fff; border-radius: 999px; font-size: 9pt; font-weight: 700; display: flex; align-items: center; justify-content: center; flex-shrink: 0; }
  .phase-body { border: 1px solid #e5e7eb; border-radius: 8px; padding: 10px 12px; background: #fafafa; flex: 1; }
  .milestone { display: inline-block; background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 6px; padding: 2px 10px; font-size: 9pt; color: #15803d; margin-top: 6px; }
  .tools-section { margin-top: 12px; border-top: 1px solid #e5e7eb; padding-top: 10px; }
  .tags { display: flex; flex-wrap: wrap; gap: 6px; margin-top: 4px; }
  .tag { background: #f3f4f6; border: 1px solid #e5e7eb; border-radius: 999px; padding: 2px 10px; font-size: 9pt; }
  .tag.amber { background: #fffbeb; border-color: #fde68a; color: #92400e; font-weight: 600; }

  /* Badges */
  .badge-cyan { background: #ecfeff; color: #0e7490; font-size: 8pt; font-weight: 600; padding: 1px 7px; border-radius: 999px; }
  .badge-green { background: #f0fdf4; color: #15803d; font-size: 8pt; font-weight: 600; padding: 1px 7px; border-radius: 999px; }

  /* Launch criteria */
  .criteria-box { border-radius: 8px; padding: 10px 12px; border: 1px solid; }
  .criteria-box.green { background: #f0fdf4; border-color: #bbf7d0; }
  .criteria-box.amber { background: #fffbeb; border-color: #fde68a; }
  .criteria-box.red { background: #fef2f2; border-color: #fecaca; }
  .crit-title { font-size: 10pt; font-weight: 600; margin-bottom: 6px; }
  .crit-title.green { color: #15803d; }
  .crit-title.amber { color: #92400e; }
  .crit-title.red { color: #dc2626; }

  /* Testing */
  .testing-table { width: 100%; border-collapse: collapse; font-size: 9.5pt; }
  .testing-table th { text-align: left; font-size: 8.5pt; font-weight: 700; text-transform: uppercase; letter-spacing: .05em; color: #6b7280; padding: 6px 10px; border-bottom: 2px solid #e5e7eb; }
  .testing-table td { padding: 6px 10px; border-bottom: 1px solid #f3f4f6; vertical-align: top; }

  /* Lists */
  ul, ol { padding-left: 18px; margin: 4px 0; }
  li { margin-bottom: 2px; font-size: 10pt; }
  a { color: #d97706; text-decoration: underline; word-break: break-all; }

  @page { size: A4; margin: 1.5cm 2cm; }
  @media print { body { padding: 0; } }
</style>
</head>
<body>
  <h1>${esc(idea.title ?? "Untitled Idea")} — MVP Plan</h1>
  ${date ? `<p class="meta-line">${date}</p>` : ""}
  ${idea.description ? `<p class="desc">${esc(idea.description)}</p>` : ""}
  ${goalHtml}
  ${assumptionsHtml}
  ${scopeHtml}
  ${flowsHtml}
  ${buildPlanHtml}
  ${experimentsHtml}
  ${launchHtml}
  ${testingHtml}
  ${firstUsersHtml}
  ${sourcesHtml}
</body>
</html>`;
}

function renderPdfValue(value: unknown, depth = 0): string {
  if (value === null || value === undefined) return "";
  if (typeof value === "string") return `<span>${esc(value)}</span>`;
  if (typeof value === "number" || typeof value === "boolean") return `<span>${String(value)}</span>`;
  if (Array.isArray(value)) {
    const items = value.filter((v) => v !== null && v !== undefined);
    if (items.length === 0) return "";
    if (items.every((v) => typeof v === "string" || typeof v === "number")) {
      return `<ul>${items.map((v) => `<li>${esc(v)}</li>`).join("")}</ul>`;
    }
    return items.map((v) => renderPdfValue(v, depth + 1)).join("");
  }
  if (typeof value === "object") {
    const entries = Object.entries(value as Record<string, unknown>).filter(
      ([, v]) => v !== null && v !== undefined && v !== ""
    );
    if (entries.length === 0) return "";
    const tag = depth === 0 ? "h3" : "h4";
    return entries
      .map(([k, v]) => {
        const label = k.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase());
        const rendered = renderPdfValue(v, depth + 1);
        if (!rendered) return "";
        return `<div class="field"><${tag}>${label}</${tag}>${rendered}</div>`;
      })
      .join("");
  }
  return "";
}

function buildSectionHtml(title: string, data: string | null): string {
  const parsed = safeParseJson(data);
  if (!parsed) return "";
  const body = renderPdfValue(parsed);
  if (!body) return "";
  return `<section><h2>${title}</h2>${body}</section>`;
}

function buildPdfHtml(idea: Idea, sections: ReturnType<typeof useAiPipeline>["sections"]): string {
  const metaRows = [
    idea.budget != null ? `<tr><td>Budget</td><td>$${idea.budget.toLocaleString()}</td></tr>` : "",
    idea.feasibility != null ? `<tr><td>Feasibility</td><td>${idea.feasibility} / 10</td></tr>` : "",
    idea.status ? `<tr><td>Status</td><td>${esc(idea.status)}</td></tr>` : "",
  ].filter(Boolean).join("");

  const sectionBlocks = [
    buildSectionHtml("Strategy", sections.ideaStrategy.data),
    buildSectionHtml("Customers", sections.customers.data),
    buildSectionHtml("Competitor Analysis", sections.competition.data),
    buildSectionHtml("Market Potential", sections.marketPotential.data),
    buildSectionHtml("Business Model", sections.businessModel.data),
    buildSectionHtml("MVP Planning", sections.mvpPlanning.data),
    buildSectionHtml("Risk & Problems", sections.problems.data),
    buildSectionHtml("Unit Economics", sections.unitEconomics.data),
  ].filter(Boolean).join("");

  const date = idea.created_at ? new Date(idea.created_at).toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }) : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<title>${esc(idea.title ?? "Idea")} — Analysis Report</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Georgia, serif; color: #111; background: #fff; padding: 2.5cm 3cm; font-size: 11pt; line-height: 1.6; }
  h1 { font-size: 22pt; font-weight: 700; margin-bottom: 4px; }
  .meta-date { color: #666; font-size: 10pt; margin-bottom: 16px; }
  .description { font-size: 11pt; color: #333; max-width: 680px; margin-bottom: 18px; white-space: pre-wrap; }
  table.meta { border-collapse: collapse; margin-bottom: 24px; }
  table.meta td { padding: 4px 16px 4px 0; font-size: 10pt; vertical-align: top; }
  table.meta td:first-child { font-weight: 600; color: #555; text-transform: uppercase; font-size: 9pt; letter-spacing: .04em; width: 120px; }
  section { margin-top: 32px; break-inside: avoid; }
  h2 { font-size: 14pt; font-weight: 700; border-bottom: 2px solid #f59e0b; padding-bottom: 4px; margin-bottom: 14px; color: #1a1a1a; }
  h3 { font-size: 11pt; font-weight: 600; margin: 12px 0 4px; color: #333; }
  h4 { font-size: 10pt; font-weight: 600; margin: 8px 0 2px; color: #444; }
  .field { margin-bottom: 10px; }
  ul { padding-left: 20px; margin: 4px 0; }
  li { margin-bottom: 2px; font-size: 10.5pt; }
  span { display: block; font-size: 10.5pt; }
  @page { size: A4; margin: 1.5cm 2cm; }
  @media print { body { padding: 0; } }
</style>
</head>
<body>
  <h1>${esc(idea.title ?? "Untitled Idea")}</h1>
  ${date ? `<p class="meta-date">${date}</p>` : ""}
  ${idea.description ? `<p class="description">${esc(idea.description)}</p>` : ""}
  ${metaRows ? `<table class="meta"><tbody>${metaRows}</tbody></table>` : ""}
  ${sectionBlocks || "<p>No AI analysis generated yet.</p>"}
</body>
</html>`;
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export default function IdeaDetailPage({
  params,
}: {
  params: Promise<{ idea_id: string }>;
}) {
  const { idea_id } = use(params);
  const [idea, setIdea]     = useState<Idea | null>(null);
  const [loading, setLoading] = useState(true);
  const [fetchError, setFetchError] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<TabKey>("overview");

  const { sections, isRunning, hasRun, runError, runPipeline, runSection, regenerateSection, regenerateSectionCustom, fetchAll } = useAiPipeline(idea_id);

  const [customPromptOpen, setCustomPromptOpen]       = useState(false);
  const [customPromptSection, setCustomPromptSection] = useState<SectionKey | null>(null);
  const [customPromptText, setCustomPromptText]       = useState("");

  const [chatPopupOpen, setChatPopupOpen]       = useState(false);
  const [chatPopupSection, setChatPopupSection] = useState<SectionKey | null>(null);

  const [editModalOpen, setEditModalOpen] = useState(false);

  const handleDownloadPDF = () => {
    if (!idea) return;
    const isMvpTab = activeTab === "mvp";
    const mvpData = isMvpTab ? sections.mvpPlanning.data : null;
    const html = isMvpTab && mvpData
      ? buildMvpPdfHtml(idea, mvpData)
      : buildPdfHtml(idea, sections);
    const win = window.open("", "_blank");
    if (!win) return;
    win.document.open();
    win.document.write(html);
    win.document.close();
    win.focus();
    setTimeout(() => win.print(), 400);
  };

  useEffect(() => {
    api
      .get<Idea>(`/ideas/${idea_id}`)
      .then(({ data }) => setIdea(data))
      .catch(() => setFetchError("Failed to load idea."))
      .finally(() => setLoading(false));
  }, [idea_id]);

  // ── Loading / error states ──────────────────────────────────────────────────

  if (loading) {
    return (
      <div className="min-h-screen bg-neutral-100 dark:bg-neutral-900 flex items-center justify-center">
        <div className="w-6 h-6 rounded-full border-2 border-amber-400 border-t-transparent animate-spin" />
      </div>
    );
  }

  if (fetchError || !idea) {
    return (
      <div className="min-h-screen bg-neutral-100 dark:bg-neutral-900 flex items-center justify-center gap-3 text-red-500">
        <AlertCircle size={18} />
        <p className="text-sm">{fetchError ?? "Idea not found."}</p>
      </div>
    );
  }

  // ── Render ──────────────────────────────────────────────────────────────────

  return (
    <div className="min-h-screen bg-neutral-100 dark:bg-neutral-900 transition-colors">
      <main className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 pb-16">

        {/* Breadcrumb */}
        <nav className="flex items-center gap-1.5 pt-6 pb-4 text-sm text-gray-500 dark:text-gray-400">
          <Link href="/entrepreneur" className="hover:text-gray-700 dark:hover:text-gray-200 transition-colors">
            <Home size={14} />
          </Link>
          <ChevronRight size={12} className="text-gray-400" />
          <Link href="/entrepreneur/ideas" className="hover:text-gray-700 dark:hover:text-gray-200 transition-colors">
            Ideas
          </Link>
          <ChevronRight size={12} className="text-gray-400" />
          <span className="text-gray-700 dark:text-gray-200 font-medium truncate max-w-[200px]">
            {idea.title ?? "Untitled idea"}
          </span>
        </nav>

        {/* Header row */}
        <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4 mb-8">
          {/* Title + date */}
          <div className="flex flex-col gap-2">
            <h1 className="text-2xl sm:text-3xl font-semibold text-foreground">{idea.title ?? "Untitled idea"}</h1>
            <p className="text-base text-muted-foreground">{formatIdeaDate(idea.created_at)}</p>
          </div>

          {/* Actions */}
          <div className="flex items-center gap-2 shrink-0">
            {/* Pipeline status */}
            {isRunning && (
              <span className="flex items-center gap-1.5 text-xs text-amber-600 dark:text-amber-400 font-medium">
                <Loader2 size={12} className="animate-spin" />
                Running pipeline…
              </span>
            )}
            {hasRun && !isRunning && (
              <span className="text-xs text-green-600 dark:text-green-400 font-medium">
                ✓ Pipeline complete
              </span>
            )}

            {/* Save as PDF + Share */}
            <div className="flex items-center gap-0.5">
              <SectionIconButton tooltip="Save as PDF" onClick={handleDownloadPDF}>
                <FileDown size={18} className="text-neutral-400" />
              </SectionIconButton>
              <SectionIconButton tooltip="Share" onClick={() => {}}>
                <Share2 size={18} className="text-neutral-400" />
              </SectionIconButton>
            </div>

            {/* Edit with AI */}
            <button
              type="button"
              onClick={() => setEditModalOpen(true)}
              disabled={isRunning}
              className={cn(
                "flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-medium text-white cursor-pointer transition-opacity",
                "bg-gradient-to-r from-amber-500 to-yellow-500 shadow-[0_2px_16px_rgba(255,183,3,0.3)] outline outline-[0.66px] outline-yellow-500/60",
                isRunning && "opacity-60 cursor-not-allowed"
              )}
            >
              <Sparkles size={14} />
              Edit with AI
            </button>
          </div>
        </div>

        {runError && (
          <p className="mb-4 text-sm text-red-500 bg-red-50 dark:bg-red-900/20 px-3 py-2 rounded-lg">
            {runError}
          </p>
        )}

        {/* Tab bar + section action icons */}
        {(() => {
          const activeSectionKey = activeTab !== "overview"
            ? TAB_STATE_KEY[activeTab as Exclude<TabKey, "overview">]
            : null;
          const activeSectionHasData = activeSectionKey ? !!sections[activeSectionKey].data : false;
          const activeSectionLoading = activeSectionKey ? sections[activeSectionKey].isLoading : false;

          return (
            <>
              <div className="sticky top-0 z-10 mb-6 py-2 bg-neutral-100 dark:bg-neutral-900 -mx-4 px-4 sm:-mx-6 sm:px-6 lg:-mx-8 lg:px-8">
                <div className="px-2 py-1.5 bg-gray-200 dark:bg-neutral-800 rounded-lg flex items-center justify-center gap-2 overflow-x-auto scrollbar-hide">
                  {TABS.map(({ key, label }) => {
                    const active = activeTab === key;
                    return (
                      <button
                        key={key}
                        type="button"
                        onClick={() => setActiveTab(key)}
                        className={cn(
                          "shrink-0 min-h-10 px-4 py-2 rounded-xl text-sm font-medium transition-all cursor-pointer whitespace-nowrap",
                          active
                            ? "bg-white dark:bg-neutral-700 text-foreground shadow-sm border border-neutral-300 dark:border-neutral-600"
                            : "text-neutral-600 dark:text-neutral-400 hover:bg-white/50 dark:hover:bg-neutral-700/50"
                        )}
                      >
                        {label}
                      </button>
                    );
                  })}
                </div>
              </div>

              {/* Section header — title + action icons */}
              {activeSectionHasData && activeSectionKey && (
                <div className="flex items-center justify-between px-4 py-2.5 mb-4 bg-card border border-border rounded-xl">
                  <span className="text-sm font-semibold text-foreground">
                    {TABS.find(t => t.key === activeTab)?.label}
                  </span>
                  <div className="flex items-center gap-0.5">
                    <SectionIconButton
                      tooltip="Regenerate"
                      disabled={activeSectionLoading}
                      onClick={() => regenerateSection(activeSectionKey)}
                    >
                      <RefreshCw size={16} />
                    </SectionIconButton>
                    <SectionIconButton
                      tooltip="Regenerate with custom prompt"
                      disabled={activeSectionLoading}
                      onClick={() => {
                        setCustomPromptSection(activeSectionKey);
                        setCustomPromptText("");
                        setCustomPromptOpen(true);
                      }}
                    >
                      <Wand2 size={16} />
                    </SectionIconButton>
                    <SectionIconButton
                      tooltip="Chat with AI"
                      onClick={() => { setChatPopupSection(activeSectionKey); setChatPopupOpen(true); }}
                    >
                      <MessageCircle size={16} />
                    </SectionIconButton>
                  </div>
                </div>
              )}
            </>
          );
        })()}

        {/* Custom prompt modal */}
        {customPromptOpen && (
          <div
            className="fixed inset-0 bg-black/40 flex items-center justify-center z-50"
            onClick={() => setCustomPromptOpen(false)}
          >
            <div
              className="bg-white dark:bg-neutral-800 rounded-2xl shadow-xl p-6 w-full max-w-md mx-4 flex flex-col gap-4"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-semibold text-foreground">Custom Regeneration</h3>
                <button
                  type="button"
                  onClick={() => setCustomPromptOpen(false)}
                  className="p-1 rounded-lg hover:bg-neutral-100 dark:hover:bg-neutral-700 transition-colors cursor-pointer"
                >
                  <X size={15} className="text-neutral-500" />
                </button>
              </div>
              <textarea
                value={customPromptText}
                onChange={(e) => setCustomPromptText(e.target.value)}
                placeholder="Describe what you want to change or focus on…"
                rows={4}
                className="w-full text-sm border border-border rounded-xl p-3 resize-none bg-transparent focus:outline-none focus:ring-2 focus:ring-amber-400 text-foreground placeholder:text-muted-foreground"
                autoFocus
              />
              <button
                type="button"
                disabled={!customPromptText.trim()}
                onClick={() => {
                  if (customPromptSection && customPromptText.trim()) {
                    regenerateSectionCustom(customPromptSection, customPromptText.trim());
                    setCustomPromptOpen(false);
                    setCustomPromptText("");
                  }
                }}
                className={cn(
                  "flex items-center justify-center gap-2 px-4 py-2.5 rounded-xl text-sm font-medium text-white transition-opacity cursor-pointer",
                  "bg-gradient-to-r from-amber-500 to-yellow-500 shadow-[0_2px_12px_rgba(255,183,3,0.3)]",
                  !customPromptText.trim() && "opacity-50 cursor-not-allowed"
                )}
              >
                <Wand2 size={14} />
                Generate
              </button>
            </div>
          </div>
        )}

        {/* Tab content */}
        <TabContent
          tab={activeTab}
          idea={idea}
          sections={sections}
          onRun={runPipeline}
          onRunSection={runSection}
          isRunning={isRunning}
        />
      </main>

      {/* Section chat popup */}
      {chatPopupOpen && chatPopupSection && (
        <SectionChatPopup
          key={chatPopupSection}
          sectionKey={chatPopupSection}
          ideaId={idea_id}
          onClose={() => setChatPopupOpen(false)}
        />
      )}

      {/* Edit Idea with AI modal */}
      {editModalOpen && idea && (
        <IdeaEditChatModal
          idea={idea}
          ideaId={idea_id}
          onClose={() => setEditModalOpen(false)}
          onSectionsReset={() => { fetchAll(); }}
        />
      )}
    </div>
  );
}

function SectionIconButton({
  tooltip,
  onClick,
  disabled,
  children,
}: {
  tooltip: string;
  onClick: () => void;
  disabled?: boolean;
  children: React.ReactNode;
}) {
  return (
    <div className="relative group">
      <button
        type="button"
        onClick={onClick}
        disabled={disabled}
        className={cn(
          "p-2 rounded-lg hover:bg-neutral-200 dark:hover:bg-neutral-700 transition-colors cursor-pointer text-neutral-500 dark:text-neutral-400",
          disabled && "opacity-40 cursor-not-allowed"
        )}
      >
        {children}
      </button>
      <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-1.5 px-2 py-1 bg-neutral-800 dark:bg-neutral-100 text-white dark:text-neutral-900 text-xs rounded-md whitespace-nowrap opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none z-20">
        {tooltip}
      </div>
    </div>
  );
}
